local StarterLoadout = {
	ActiveWeaponSlot = "Melee",
	BodyType = "Male",
	Weapons = {
		Melee = "TrainingKatana",
		Primary1 = "TrainingShotgun",
		Primary2 = "TrainingShotgun",
	},
	Equipment = {
		Equipment1 = "VitalPatch",
		Equipment2 = "AegisPatch",
		Equipment3 = "VitalAmp",
		Equipment4 = "AegisAmp",
	},
	Armour = {
		Head = "",
		Body = "",
		Legs = "",
		Feet = "",
	},
	Rings = {
		Ring1 = "",
		Ring2 = "",
	},
}

return StarterLoadout
